[sortbenchmark]
version = 1.0.0 (sortbenchmark)

[helper]
instrument = false
seed = 0
cutoff = 1

[instrumenting]
# The options in this section apply only if instrument = true
showStats = true
swaps = true
compares = true
copies = true
fixes = false
hits = true
inversions = 0

[benchmarkstringsorters]
words = 1000
runs = 20
mergesort = true
quicksort = false
quicksortDualPivot = true
heapsort = true
timsort = false
insertionsort = false
introsort = false
bubblesort = false
quicksort3way = false
randomsort = false

[benchmarkdatesorters]
timsort = false
n = 100000

[mergesort]
insurance = false
nocopy = true
